name = "evm-panel-next"
compatibility_date = "2024-03-20"

[dev]
ip = "127.0.0.1"
port = 8787

[observability.logs]
enabled = true

# Binding for KV Namespace
[[kv_namespaces]]
binding = "EVM_PANEL_KV"
id = "db1d81cf8e2b4991bbe8af9a039e5974"
preview_id = "db1d81cf8e2b4991bbe8af9a039e5974"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Secrets
# Important: You must set the PINATA_JWT secret in your Cloudflare dashboard
# or by running `npx wrangler secret put PINATA_JWT`
# PINATA_JWT = "your_pinata_jwt_here"